export const SET_SOURCE_AUDIO = 'SET_SOURCE_AUDIO';
export const SET_SPECTROGRAM = 'SET_SPECTROGRAM';
export const APPEND_NOTE = 'APPEND_NOTE';
export const INSERT_MODULATION = 'INSERT_MODULATION';
export const INSERT_NOTE_OFF = 'INSERT_NOTE_OFF';
